const express=require('express');const cors=require('cors');const path=require('path');const fs=require('fs');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'change-this-in-production';
app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,'../public')));
const file=path.join(__dirname,'../data/db.json');const seed={users:[],events:[{id:1,time:'10:00 AM',title:'Research Workshop',venue:'Seminar Hall 2'},{id:2,time:'1:00 PM',title:'Students Union Meeting',venue:'Union Hall'},{id:3,time:'4:00 PM',title:'Cultural Programme',venue:'Open Air Auditorium'}],opportunities:[{id:1,type:'SCHOLARSHIP',title:'OBC Post-Matric Scholarship',deadline:'2026-11-30',description:'Post-matric scholarship opportunity.'},{id:2,type:'SCHOLARSHIP',title:'Special Scholarship for OBC Girls',deadline:'2026-09-15',description:'Special scholarship opportunity.'},{id:3,type:'INTERNSHIP',title:'Research Internship',deadline:'2026-12-31',description:'Research internship listing.'}],polls:[{id:1,question:'What should the Union prioritise?',options:['Library','Transport','Food','Student services'],votes:[0,0,0,0]}],grievances:[],questions:[]};
if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify(seed,null,2));const db=()=>JSON.parse(fs.readFileSync(file));const save=d=>fs.writeFileSync(file,JSON.stringify(d,null,2));
function auth(req,res,next){try{const h=req.headers.authorization||'';req.user=jwt.verify(h.replace('Bearer ',''),SECRET);next()}catch(e){res.status(401).json({error:'Authentication required'})}}
app.post('/api/auth/register',async(req,res)=>{const {name,email,password,programme='Integrated M.Sc. Statistics',year='2nd Year'}=req.body;if(!name||!email||!password)return res.status(400).json({error:'name, email and password required'});let d=db();if(d.users.some(u=>u.email===email))return res.status(409).json({error:'Email already registered'});const u={id:Date.now(),name,email,password:await bcrypt.hash(password,10),programme,year,activities:0,certificates:0};d.users.push(u);save(d);const token=jwt.sign({id:u.id,email:u.email},SECRET,{expiresIn:'7d'});delete u.password;res.json({token,user:u})});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body,d=db(),u=d.users.find(x=>x.email===email);if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({error:'Invalid credentials'});const token=jwt.sign({id:u.id,email:u.email},SECRET,{expiresIn:'7d'});const user={...u};delete user.password;res.json({token,user})});
app.get('/api/me',auth,(req,res)=>{const u=db().users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:'User not found'});const user={...u};delete user.password;res.json(user)});
app.get('/api/home',(req,res)=>{const d=db();res.json({events:d.events,opportunities:d.opportunities.slice(0,3),polls:d.polls})});
app.get('/api/events',(req,res)=>res.json(db().events));app.get('/api/opportunities',(req,res)=>res.json(db().opportunities));app.get('/api/polls',(req,res)=>res.json(db().polls));
app.post('/api/polls/:id/vote',auth,(req,res)=>{const {option}=req.body,d=db(),p=d.polls.find(x=>x.id==req.params.id);if(!p||option<0||option>=p.options.length)return res.status(400).json({error:'Invalid poll option'});p.votes[option]++;save(d);res.json(p)});
app.post('/api/grievances',auth,(req,res)=>{const {title,description,category='General'}=req.body;if(!title||!description)return res.status(400).json({error:'Title and description required'});const d=db(),g={id:'GRV-'+Date.now(),userId:req.user.id,title,description,category,status:'Submitted',createdAt:new Date().toISOString(),history:[{status:'Submitted',at:new Date().toISOString()}]};d.grievances.push(g);save(d);res.status(201).json(g)});
app.get('/api/grievances',auth,(req,res)=>res.json(db().grievances.filter(g=>g.userId===req.user.id)));
app.get('/api/campus',(req,res)=>res.json([{id:1,name:'CUSAT Main Block',type:'Building',x:'12%',y:'20%'},{id:2,name:'University Library',type:'Library',x:'70%',y:'35%'},{id:3,name:'Statistics Department',type:'Department',x:'30%',y:'70%'},{id:4,name:'Union Hall',type:'Union',x:'65%',y:'75%'}]));
app.post('/api/ask',async(req,res)=>{const q=String(req.body.question||'').toLowerCase().trim();if(!q)return res.status(400).json({error:'Question required'});let answer='I could not find a verified answer yet. Please check the official CUSAT/Union information source.';let source='CUSSApp verified knowledge base';if(q.includes('statistics'))answer='The Statistics Department is available on the CUSSApp Campus map. Open Campus and search for “Statistics Department”.';else if(q.includes('scholar'))answer='Open Opportunities → Scholarships to see currently listed scholarships, eligibility and deadlines. Each listing should link to its verified source.';else if(q.includes('report')||q.includes('issue')||q.includes('grievance'))answer='Use the Grievance section to submit an issue. You can track it through Submitted → Received → Under Review → Forwarded → Action Taken → Resolved.';const d=db();d.questions.push({id:Date.now(),question:q,answer,at:new Date().toISOString()});save(d);res.json({answer,source})});
app.get('/{*splat}',(req,res)=>res.sendFile(path.join(__dirname,'../public/index.html')));

if (require.main === module) {
	app.listen(PORT,()=>console.log(`CUSSApp running at http://localhost:${PORT}`));
}

module.exports = app;
